version: '3'
services:
  ui:
    image: "node:fermium-bullseye"
    user: node
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    command: "npm start"
    depends_on:
      - api
  api:
    image: golang:1.17-bullseye
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: "go run main.go"
    depends_on:
      - redis
  nginx:
    image: nginx:1.20-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - api
      - ui
  redis:
    image: redis:6.2-alpine
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis