version: '3'
services:
  redis:
    image: redis:6.2-alpine
  ui:
    build: 
      context: .
      dockerfile: DockerfileUI
    expose:
      - 3000
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    expose:
      - 5000
    depends_on:
      - redis
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/neohooks.site.conf
    depends_on:
      - api
      - ui
      
volumes:
  nginx_secrets: