# docker-compose file for local dev
version: '3'
services:
  redis:
    image: redis:6.2-alpine
    volumes:
      - "./conf/redis/dev/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  ui:
    image: "node:fermium-bullseye"
    user: node
    working_dir: /home/node/app
    expose:
      - 3000
    volumes:
      - ./ui:/home/node/app
    command: "npm start"
    depends_on:
      - api
  api:
    image: golang:1.17
    working_dir: /app
    expose:
      - 5000
    volumes:
      - ./api:/app
    command: go run main.go
    depends_on:
      - redis
  nginx:
    image: nginx:1.21-alpine
    volumes:                                              
      - "./conf/nginx/dev/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/dev/certs:/etc/nginx/certs"                  
    ports:
      - "8443:443"  
    depends_on:
      - api
      - ui
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis