# docker-compose file for local dev (prod file will be added later)
version: '3'
services:
  redis:
    image: redis:6.2-alpine
  ui:
    build: DockerfileUI
    expose:
      - 3000
    depends_on:
      - api
  api:
    build: DockerfileAPI
    expose:
      - 5000
    depends_on:
      - redis
  nginx:
    build: DockerfileNginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"  
    depends_on:
      - api
      - ui