version: '3'
services:
  redis:
    image: redis:6.2-alpine
    volumes:
      - "./conf/redis/prod/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
  ui:
    build: ui/
    expose:
      - 3000
    depends_on:
      - api
  api:
    build: api/
    expose:
      - 5000
    depends_on:
      - redis
  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx/prod/nginx.conf:/etc/nginx/conf.d/neohooks.site.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - web_root:/var/www/html
    depends_on:
      - api
      - ui
  certbot:
    image: certbot/certbot
    environment:
      - CERTBOT_EMAIL
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - web_root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email $CERTBOT_EMAIL --agree-tos --no-eff-email -d neohooks.site -d www.neohooks.site
    depends_on:
      - nginx

volumes:
  certbot_etc:
  certbot_var:
  web_root:
    driver: local
