name: GitHub
on:
  push: 
    branches:
      - dev

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: ${{ github.repository }}-api
  UI_IMAGE_NAME: ${{ github.repository }}-ui

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a command
        run: echo Chintu, World!
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract metadata (tags, labels) for neohooks API
        id: api_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
      - name: Extract metadata (tags, labels) for neohooks API
        id: ui_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.UI_IMAGE_NAME }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: api/Dockerfile
          push: true
          tags: ${{ steps.api_meta.outputs.tags }}
          labels: ${{ steps.api_meta.outputs.labels }}
      - name: Build and push UI
        uses: docker/build-push-action@v2
        with:
          context: web/
          file: web/Dockerfile
          push: true
          tags: ${{ steps.ui_meta.outputs.tags }}
          labels: ${{ steps.ui_meta.outputs.labels }}